export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// USER
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
